### ISSUE TITLE
Any training examples?Error happens when opt.compute_gradients(lossCTC)

### ISSUE THREAD

**Issue by DaoZhang0123** [jianlong-yuan/syncbn-tensorflow#8]
I run this code with a training optimizer, but get below errors:
`Traceback (most recent call last):
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2349, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'tower_0/lstm2fc/batch_normalization_0/NcclAllReduce_1' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 391, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2353, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'tower_0/lstm2fc/batch_normalization_0/NcclAllReduce_1' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "src/train_net.py", line 149, in training
    sw.trainModel(maxIters=parseArg.maxIters, restore=parseArg.restore)
  File "src/../src/lib/train.py", line 116, in trainModel
    gradItem = opt.compute_gradients(self.lossCTC)
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 511, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 532, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 396, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/dao/anaconda2/envs/python36/lib/python3.6/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 65, in _all_sum_grad
    raise LookupError('No gradient defined for NcclAllReduce except sum.')
LookupError: No gradient defined for NcclAllReduce except sum.
`
Error happend when compute the gradients:
`gradItem = opt.compute_gradients(lossCTC)`

**Comment by hoL1day** [comment]
@wangershi Hello, I have the same problem. How did you solve it?

**Comment by DaoZhang0123** [comment]
@hoL1day Yeah, I solve it, you can see it in my [code](https://github.com/wangershi/testBNInMultiGPU/blob/master/validSyncBN.py), I guess you are Chinese, so you can see my [blog](https://zhuanlan.zhihu.com/p/69267784) for more details.

**Comment by hoL1day** [comment]
@wangershi Thanks a lot! 
 I got the same "No gradient defined for NcclAllReduce except sum" error while opt.compute_gradients(loss), but I simply looked at the code and didn't see the part of compute_gradients.

**Comment by DaoZhang0123** [comment]
@hoL1day First, this code is about BN, you should define loss function in other functions.
Second, I noticed you realized that the error come from gradient computing, and you can see there are somes [Python judge function](https://github.com/jianlong-yuan/syncbn-tensorflow/blob/1c9debc202e936657d96eece27b9a77606827eb1/syncbn.py#L50), which can not be imported in TF graph, therefore TF can't compute its gradients automatically:
```if is_training and trainable:```
And I use standard function [tf.cond()](https://www.tensorflow.org/api_docs/python/tf/cond) to solve this problem:
```
outputs, batch_mean, batch_var = tf.cond(tf.math.logical_and(training, trainable), branchTrue, branchFalse)
```

**Comment by hoL1day** [comment]
@wangershi Thanks a lot! Your blog is really helpful!
I may figure out the problem. It came from $PYTHON/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py :65
`if op.get_attr('reduction') != 'sum':`
But I found tha op.get_attr('reduction') is b'sum', so I change to code to
`if op.get_attr('reduction') != 'sum' and op.get_attr('reduction') != b'sum':`
and also change :70 from
`shared_name = op.get_attr('shared_name') + '_grad'`
to
`shared_name = op.get_attr('shared_name') + b'_grad'`

May this will help others~
